version: '3.1'

services:

  redmine:
    image: redmine
    restart: always
    ports:
      - 8080:3000
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: example
    volumes:
      - "./configuration.yml:/usr/src/redmine/config/configuration.yml"

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: redmine
    volumes:
      - "./mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf"
      - "./mysql:/var/lib/mysql"